version: '3'
services:
  db:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_DB: tjv
      POSTGRES_USER: tjv
      POSTGRES_PASSWORD: tjv
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./data.sql:/data.sql

  server:
    build: 
      context: ./cs_skin_system
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tjv

  client:
    build: 
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - '5173:5173'

volumes:
  dbdata: